[2025-04-09 05:15:09,433] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 05:15:09,433] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: aabbcc1
[2025-04-09 05:15:09,469] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc1
[2025-04-09 05:15:09,469] INFO api.views.data_upload_view - Procesando entrada con clave: 2 y ID: aabbcc2
[2025-04-09 05:15:09,470] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc2
[2025-04-09 05:15:09,470] INFO api.views.data_upload_view - Procesando entrada con clave: 3 y ID: aabbcc3
[2025-04-09 05:15:09,471] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc3
[2025-04-09 05:15:09,471] INFO api.views.data_upload_view - Procesando entrada con clave: 4 y ID: aabbcc4
[2025-04-09 05:15:09,472] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc4
[2025-04-09 05:15:09,472] INFO api.views.data_upload_view - Procesando entrada con clave: 5 y ID: aabbcc5
[2025-04-09 05:15:09,473] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc5
[2025-04-09 05:15:09,473] INFO api.views.data_upload_view - Procesando entrada con clave: 6 y ID: aabbcc6
[2025-04-09 05:15:09,476] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc6
[2025-04-09 05:15:09,477] INFO api.views.data_upload_view - Procesando entrada con clave: 7 y ID: aabbcc7
[2025-04-09 05:15:09,478] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc7
[2025-04-09 05:15:09,478] INFO api.views.data_upload_view - Procesando entrada con clave: 8 y ID: aabbcc8
[2025-04-09 05:15:09,479] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc8
[2025-04-09 05:15:09,479] INFO api.views.data_upload_view - Procesando entrada con clave: 9 y ID: aabbcc9
[2025-04-09 05:15:09,479] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc9
[2025-04-09 05:15:09,479] INFO api.views.data_upload_view - Procesando entrada con clave: 10 y ID: aabbcc10
[2025-04-09 05:15:09,480] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc10
[2025-04-09 05:15:09,480] INFO api.views.data_upload_view - Procesando entrada con clave: 11 y ID: aabbcc11
[2025-04-09 05:15:09,481] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc11
[2025-04-09 05:15:09,481] INFO api.views.data_upload_view - Procesando entrada con clave: 12 y ID: aabbcc12
[2025-04-09 05:15:09,481] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc12
[2025-04-09 05:15:09,481] INFO api.views.data_upload_view - Procesando entrada con clave: 13 y ID: aabbcc13
[2025-04-09 05:15:09,482] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc13
[2025-04-09 05:15:09,482] INFO api.views.data_upload_view - Procesando entrada con clave: 14 y ID: aabbcc14
[2025-04-09 05:15:09,483] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc14
[2025-04-09 05:15:09,483] INFO api.views.data_upload_view - Procesando entrada con clave: 15 y ID: aabbcc15
[2025-04-09 05:15:09,484] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc15
[2025-04-09 05:15:09,484] INFO api.views.data_upload_view - Procesando entrada con clave: 16 y ID: aabbcc16
[2025-04-09 05:15:09,485] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc16
[2025-04-09 05:15:09,485] INFO api.views.data_upload_view - Procesando entrada con clave: 17 y ID: aabbcc17
[2025-04-09 05:15:09,486] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc17
[2025-04-09 05:15:09,486] INFO api.views.data_upload_view - Procesando entrada con clave: 18 y ID: aabbcc18
[2025-04-09 05:15:09,487] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc18
[2025-04-09 05:15:09,487] INFO api.views.data_upload_view - Procesando entrada con clave: 19 y ID: aabbcc19
[2025-04-09 05:15:09,487] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc19
[2025-04-09 05:15:09,488] INFO api.views.data_upload_view - Procesando entrada con clave: 20 y ID: aabbcc20
[2025-04-09 05:15:09,488] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc20
[2025-04-09 05:15:09,488] INFO api.views.data_upload_view - Procesando entrada con clave: 21 y ID: aabbcc21
[2025-04-09 05:15:09,489] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc21
[2025-04-09 05:15:09,489] INFO api.views.data_upload_view - Procesando entrada con clave: 22 y ID: aabbcc22
[2025-04-09 05:15:09,490] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc22
[2025-04-09 05:15:09,490] INFO api.views.data_upload_view - Procesando entrada con clave: 23 y ID: aabbcc23
[2025-04-09 05:15:09,491] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc23
[2025-04-09 05:15:09,491] INFO api.views.data_upload_view - Procesando entrada con clave: 24 y ID: aabbcc24
[2025-04-09 05:15:09,492] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc24
[2025-04-09 05:15:09,492] INFO api.views.data_upload_view - Procesando entrada con clave: 25 y ID: aabbcc25
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc25
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Procesando entrada con clave: 26 y ID: aabbcc26
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc26
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Procesando entrada con clave: 27 y ID: aabbcc27
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc27
[2025-04-09 05:15:09,494] INFO api.views.data_upload_view - Procesando entrada con clave: 28 y ID: aabbcc28
[2025-04-09 05:15:09,495] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc28
[2025-04-09 05:15:09,495] INFO api.views.data_upload_view - Procesando entrada con clave: 29 y ID: aabbcc29
[2025-04-09 05:15:09,497] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc29
[2025-04-09 05:15:09,497] INFO api.views.data_upload_view - Procesando entrada con clave: 30 y ID: aabbcc30
[2025-04-09 05:15:09,497] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc30
[2025-04-09 05:15:09,497] INFO api.views.data_upload_view - Procesando entrada con clave: 31 y ID: aabbcc31
[2025-04-09 05:15:09,498] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc31
[2025-04-09 05:15:09,498] INFO api.views.data_upload_view - Procesando entrada con clave: 32 y ID: aabbcc32
[2025-04-09 05:15:09,499] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc32
[2025-04-09 05:15:09,499] INFO api.views.data_upload_view - Procesando entrada con clave: 33 y ID: aabbcc33
[2025-04-09 05:15:09,500] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc33
[2025-04-09 05:15:09,500] INFO api.views.data_upload_view - Procesando entrada con clave: 34 y ID: aabbcc34
[2025-04-09 05:15:09,501] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc34
[2025-04-09 05:15:09,501] INFO api.views.data_upload_view - Procesando entrada con clave: 35 y ID: aabbcc35
[2025-04-09 05:15:09,502] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc35
[2025-04-09 05:15:09,502] INFO api.views.data_upload_view - Procesando entrada con clave: 36 y ID: aabbcc36
[2025-04-09 05:15:09,502] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc36
[2025-04-09 05:15:09,503] INFO api.views.data_upload_view - Procesando entrada con clave: 37 y ID: aabbcc37
[2025-04-09 05:15:09,503] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc37
[2025-04-09 05:15:09,503] INFO api.views.data_upload_view - Procesando entrada con clave: 38 y ID: aabbcc38
[2025-04-09 05:15:09,504] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc38
[2025-04-09 05:15:09,504] INFO api.views.data_upload_view - Procesando entrada con clave: 39 y ID: aabbcc39
[2025-04-09 05:15:09,505] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc39
[2025-04-09 05:15:09,505] INFO api.views.data_upload_view - Procesando entrada con clave: 40 y ID: aabbcc40
[2025-04-09 05:15:09,506] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc40
[2025-04-09 05:15:09,506] INFO api.views.data_upload_view - Procesando entrada con clave: 41 y ID: aabbcc41
[2025-04-09 05:15:09,507] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc41
[2025-04-09 05:15:09,507] INFO api.views.data_upload_view - Procesando entrada con clave: 42 y ID: aabbcc42
[2025-04-09 05:15:09,508] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc42
[2025-04-09 05:15:09,508] INFO api.views.data_upload_view - Procesando entrada con clave: 43 y ID: aabbcc43
[2025-04-09 05:15:09,508] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc43
[2025-04-09 05:15:09,509] INFO api.views.data_upload_view - Procesando entrada con clave: 44 y ID: aabbcc44
[2025-04-09 05:15:09,509] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc44
[2025-04-09 05:15:09,509] INFO api.views.data_upload_view - Procesando entrada con clave: 45 y ID: aabbcc45
[2025-04-09 05:15:09,510] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc45
[2025-04-09 05:15:09,510] INFO api.views.data_upload_view - Procesando entrada con clave: 46 y ID: aabbcc46
[2025-04-09 05:15:09,511] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc46
[2025-04-09 05:15:09,511] INFO api.views.data_upload_view - Procesando entrada con clave: 47 y ID: aabbcc47
[2025-04-09 05:15:09,512] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc47
[2025-04-09 05:15:09,512] INFO api.views.data_upload_view - Procesando entrada con clave: 48 y ID: aabbcc48
[2025-04-09 05:15:09,513] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc48
[2025-04-09 05:15:09,513] INFO api.views.data_upload_view - Procesando entrada con clave: 49 y ID: aabbcc49
[2025-04-09 05:15:09,515] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc49
[2025-04-09 05:15:09,515] INFO api.views.data_upload_view - Procesando entrada con clave: 50 y ID: aabbcc50
[2025-04-09 05:15:09,516] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbcc50
[2025-04-09 05:15:09,516] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 50
[2025-04-09 05:15:09,517] INFO django.server - "POST /api/data/ HTTP/1.1" 201 618
[2025-04-09 05:15:33,867] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 05:15:33,907] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: aabbccdd1
[2025-04-09 05:15:34,019] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd1
[2025-04-09 05:15:34,020] INFO api.views.data_upload_view - Procesando entrada con clave: 2 y ID: aabbccdd2
[2025-04-09 05:15:34,100] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd2
[2025-04-09 05:15:34,100] INFO api.views.data_upload_view - Procesando entrada con clave: 3 y ID: aabbccdd3
[2025-04-09 05:15:34,181] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd3
[2025-04-09 05:15:34,181] INFO api.views.data_upload_view - Procesando entrada con clave: 4 y ID: aabbccdd4
[2025-04-09 05:15:34,261] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd4
[2025-04-09 05:15:34,261] INFO api.views.data_upload_view - Procesando entrada con clave: 5 y ID: aabbccdd5
[2025-04-09 05:15:34,341] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd5
[2025-04-09 05:15:34,341] INFO api.views.data_upload_view - Procesando entrada con clave: 6 y ID: aabbccdd6
[2025-04-09 05:15:34,417] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd6
[2025-04-09 05:15:34,417] INFO api.views.data_upload_view - Procesando entrada con clave: 7 y ID: aabbccdd7
[2025-04-09 05:15:34,495] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd7
[2025-04-09 05:15:34,495] INFO api.views.data_upload_view - Procesando entrada con clave: 8 y ID: aabbccdd8
[2025-04-09 05:15:34,573] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd8
[2025-04-09 05:15:34,573] INFO api.views.data_upload_view - Procesando entrada con clave: 9 y ID: aabbccdd9
[2025-04-09 05:15:34,693] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd9
[2025-04-09 05:15:34,693] INFO api.views.data_upload_view - Procesando entrada con clave: 10 y ID: aabbccdd10
[2025-04-09 05:15:34,769] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd10
[2025-04-09 05:15:34,769] INFO api.views.data_upload_view - Procesando entrada con clave: 11 y ID: aabbccdd11
[2025-04-09 05:15:34,850] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd11
[2025-04-09 05:15:34,850] INFO api.views.data_upload_view - Procesando entrada con clave: 12 y ID: aabbccdd12
[2025-04-09 05:15:34,932] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd12
[2025-04-09 05:15:34,932] INFO api.views.data_upload_view - Procesando entrada con clave: 13 y ID: aabbccdd13
[2025-04-09 05:15:35,011] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd13
[2025-04-09 05:15:35,011] INFO api.views.data_upload_view - Procesando entrada con clave: 14 y ID: aabbccdd14
[2025-04-09 05:15:35,089] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd14
[2025-04-09 05:15:35,089] INFO api.views.data_upload_view - Procesando entrada con clave: 15 y ID: aabbccdd15
[2025-04-09 05:15:35,167] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd15
[2025-04-09 05:15:35,167] INFO api.views.data_upload_view - Procesando entrada con clave: 16 y ID: aabbccdd16
[2025-04-09 05:15:35,242] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd16
[2025-04-09 05:15:35,243] INFO api.views.data_upload_view - Procesando entrada con clave: 17 y ID: aabbccdd17
[2025-04-09 05:15:35,319] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd17
[2025-04-09 05:15:35,319] INFO api.views.data_upload_view - Procesando entrada con clave: 18 y ID: aabbccdd18
[2025-04-09 05:15:35,396] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd18
[2025-04-09 05:15:35,396] INFO api.views.data_upload_view - Procesando entrada con clave: 19 y ID: aabbccdd19
[2025-04-09 05:15:35,471] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd19
[2025-04-09 05:15:35,471] INFO api.views.data_upload_view - Procesando entrada con clave: 20 y ID: aabbccdd20
[2025-04-09 05:15:35,592] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: aabbccdd20
[2025-04-09 05:15:35,592] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 20
[2025-04-09 05:15:35,593] INFO django.server - "POST /api/data/ HTTP/1.1" 201 328
[2025-04-09 05:15:58,952] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 05:15:58,952] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: aabbccdd1
[2025-04-09 05:15:58,981] WARNING django.request - Bad Request: /api/data/
[2025-04-09 05:15:58,981] WARNING django.server - "POST /api/data/ HTTP/1.1" 400 162
[2025-04-09 19:54:24,625] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 19:54:38,765] WARNING django.request - Method Not Allowed: /api/data/
[2025-04-09 19:54:38,766] WARNING django.server - "GET /api/data/ HTTP/1.1" 405 40
[2025-04-09 19:56:34,893] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 19:56:35,346] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 19:56:41,037] WARNING django.request - Method Not Allowed: /api/data/
[2025-04-09 19:56:41,037] WARNING django.server - "POST /api/data/ HTTP/1.1" 405 41
[2025-04-09 19:56:51,688] ERROR django.request - Internal Server Error: /api/data/
Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'ResultEntry' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py", line 52, in get
    logger.info(f"Finalicé la consulta. Total de registros encontrados: {len(serializer.data)}")
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 715, in to_representation
    return [
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `data` on serializer `DataSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ResultEntry` instance.
Original exception text was: 'ResultEntry' object has no attribute 'data'.
[2025-04-09 19:56:51,690] ERROR django.server - "GET /api/data/ HTTP/1.1" 500 141074
[2025-04-09 19:57:08,544] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 19:57:08,981] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 19:57:12,678] WARNING django.request - Method Not Allowed: /api/data/
[2025-04-09 19:57:12,678] WARNING django.server - "POST /api/data/ HTTP/1.1" 405 41
[2025-04-09 19:58:29,120] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 19:58:29,121] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: aabbccdd1
[2025-04-09 19:58:29,162] WARNING django.request - Bad Request: /api/data/upload/
[2025-04-09 19:58:29,162] WARNING django.server - "POST /api/data/upload/ HTTP/1.1" 400 162
[2025-04-09 19:58:36,007] ERROR django.request - Internal Server Error: /api/data/
Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'ResultEntry' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py", line 52, in get
    logger.info(f"Finalicé la consulta. Total de registros encontrados: {len(serializer.data)}")
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 715, in to_representation
    return [
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `data` on serializer `DataSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ResultEntry` instance.
Original exception text was: 'ResultEntry' object has no attribute 'data'.
[2025-04-09 19:58:36,009] ERROR django.server - "GET /api/data/ HTTP/1.1" 500 141074
[2025-04-09 19:59:25,053] ERROR django.request - Internal Server Error: /api/data/
Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'ResultEntry' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py", line 52, in get
    logger.info(f"Finalicé la consulta. Total de registros encontrados: {len(serializer.data)}")
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 715, in to_representation
    return [
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `data` on serializer `DataSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ResultEntry` instance.
Original exception text was: 'ResultEntry' object has no attribute 'data'.
[2025-04-09 19:59:25,054] ERROR django.server - "GET /api/data/ HTTP/1.1" 500 141074
[2025-04-09 20:02:15,364] ERROR django.request - Internal Server Error: /api/data/
Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'ResultEntry' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py", line 52, in get
    logger.info(f"Finalicé la consulta. Total de registros encontrados: {len(serializer.data)}")
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 715, in to_representation
    return [
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\env\lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `data` on serializer `DataSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ResultEntry` instance.
Original exception text was: 'ResultEntry' object has no attribute 'data'.
[2025-04-09 20:02:15,365] ERROR django.server - "GET /api/data/ HTTP/1.1" 500 141074
[2025-04-09 20:02:19,133] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py changed, reloading.
[2025-04-09 20:02:19,599] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:02:23,470] INFO django.server - "GET /api/data/ HTTP/1.1" 200 15435
[2025-04-09 20:09:15,184] INFO django.server - "GET /api/data/?created_date__gte=2025-04-01T00:00:00Z%0A HTTP/1.1" 200 15435
[2025-04-09 20:09:24,378] INFO django.server - "GET /api/data/?updated_date__lt=2025-04-08T12:00:00Z HTTP/1.1" 200 2
[2025-04-09 20:09:37,488] INFO django.server - "GET /api/data/?created_date__gte=2024-04-01T00:00:00Z%0A HTTP/1.1" 200 15435
[2025-04-09 20:09:43,123] INFO django.server - "GET /api/data/?updated_date__lt=2024-04-08T12:00:00Z HTTP/1.1" 200 2
[2025-04-09 20:10:14,883] INFO django.server - "GET /api/data/?created_date__gte=2025-04-01T00:00:00Z%0A HTTP/1.1" 200 15435
[2025-04-09 20:10:19,139] INFO django.server - "GET /api/data/?updated_date__lt=2024-04-08T12:00:00Z HTTP/1.1" 200 2
[2025-04-09 20:10:25,914] INFO django.server - "GET /api/data/?updated_date__lt=2026-04-08T12:00:00Z HTTP/1.1" 200 15435
[2025-04-09 20:10:42,297] INFO django.server - "GET /api/data/?average_before_normalization__exact=55.0 HTTP/1.1" 200 2
[2025-04-09 20:11:07,603] INFO django.server - "GET /api/data/?average_before_normalization__exact=0.462 HTTP/1.1" 200 2
[2025-04-09 20:11:22,160] INFO django.server - "GET /api/data/?average_before_normalization__exact=0,462 HTTP/1.1" 200 15435
[2025-04-09 20:12:10,935] INFO django.server - "GET /api/data/?average_before_normalization__exact=47.54 HTTP/1.1" 200 438
[2025-04-09 20:12:28,829] INFO django.server - "GET /api/data/?average_before_normalization__gt=50 HTTP/1.1" 200 8829
[2025-04-09 20:12:35,568] INFO django.server - "GET /api/data/?average_before_normalization__lte=60 HTTP/1.1" 200 14782
[2025-04-09 20:12:44,754] INFO django.server - "GET /api/data/?average_after_normalization__gte=0.4 HTTP/1.1" 200 15435
[2025-04-09 20:13:08,494] INFO django.server - "GET /api/data/?data_size__exact=50 HTTP/1.1" 200 10921
[2025-04-09 20:13:19,142] INFO django.server - "GET /api/data/?created_date__gte=2025-04-01T00:00:00Z&average_before_normalization__gt=45&data_size__lte=150 HTTP/1.1" 200 9834
[2025-04-09 20:26:22,675] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 20:26:23,144] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:27:11,910] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 20:27:12,334] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:27:26,724] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:27:29,774] WARNING django.request - Not Found: /api/data/aabbcchjkk1/
[2025-04-09 20:27:29,774] WARNING django.server - "GET /api/data/aabbcchjkk1/ HTTP/1.1" 404 67
[2025-04-09 20:27:36,813] INFO django.server - "GET /api/data/aabbccdd1/ HTTP/1.1" 200 224
[2025-04-09 20:27:39,853] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:28:46,679] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 20:28:47,111] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:28:52,233] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:29:02,158] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:29:03,302] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:29:05,367] INFO django.server - "GET /api/data/?created_date__gte=2025-04-01T00:00:00Z&average_before_normalization__gt=45&data_size__lte=150 HTTP/1.1" 200 9834
[2025-04-09 20:29:44,467] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 20:29:44,911] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:29:47,307] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\views\data_retrieve_view.py changed, reloading.
[2025-04-09 20:29:47,745] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:29:49,395] INFO api.views.data_retrieve_view - Inicié la consulta de datos con filtros opcionales.
[2025-04-09 20:29:49,396] INFO api.views.data_retrieve_view - Apliqué filtro: created_date__gte=2025-04-01 00:00:00+00:00
[2025-04-09 20:29:49,396] INFO api.views.data_retrieve_view - Apliqué filtro: average_before_normalization__gt=45
[2025-04-09 20:29:49,396] INFO api.views.data_retrieve_view - Apliqué filtro: data_size__lte=150
[2025-04-09 20:29:49,453] INFO api.views.data_retrieve_view - Finalicé la consulta. Total de registros encontrados: 45
[2025-04-09 20:29:49,453] INFO django.server - "GET /api/data/?created_date__gte=2025-04-01T00:00:00Z&average_before_normalization__gt=45&data_size__lte=150 HTTP/1.1" 200 9834
[2025-04-09 20:30:00,623] INFO api.views.data_retrieve_view - Consulta exitosa para ID: aabbcc1
[2025-04-09 20:30:00,624] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:30:06,694] WARNING api.views.data_retrieve_view - No encontré ningún registro con ID: aabbcssc1
[2025-04-09 20:30:06,695] WARNING django.request - Not Found: /api/data/aabbcssc1/
[2025-04-09 20:30:06,695] WARNING django.server - "GET /api/data/aabbcssc1/ HTTP/1.1" 404 65
[2025-04-09 20:30:13,782] INFO api.views.data_retrieve_view - Consulta exitosa para ID: aabbcc1
[2025-04-09 20:30:13,784] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 218
[2025-04-09 20:39:28,446] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 20:39:28,892] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:39:30,248] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 20:39:30,700] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 20:41:09,538] INFO api.views.data_update_view - Inicié solicitud PUT para actualizar la entrada con ID actual: aabbcc1
[2025-04-09 20:41:09,575] INFO api.views.data_update_view - Entrada actualizada correctamente. Nuevo estado: {'id': 'aabbcc1'}
[2025-04-09 20:41:09,576] INFO django.server - "PUT /api/data/update/aabbcc1/ HTTP/1.1" 200 48
[2025-04-09 20:41:27,869] INFO api.views.data_retrieve_view - Consulta exitosa para ID: aabbcc1
[2025-04-09 20:41:27,875] INFO django.server - "GET /api/data/aabbcc1/ HTTP/1.1" 200 227
[2025-04-09 20:42:27,017] INFO api.views.data_update_view - Inicié solicitud PUT para actualizar la entrada con ID actual: aabbcc2
[2025-04-09 20:42:27,048] INFO api.views.data_update_view - Entrada actualizada correctamente. Nuevo estado: {'id': 'cambio de id'}
[2025-04-09 20:42:27,048] INFO django.server - "PUT /api/data/update/aabbcc2/ HTTP/1.1" 200 48
[2025-04-09 21:27:24,593] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\api\urls.py changed, reloading.
[2025-04-09 21:27:25,057] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:27:43,299] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 21:27:43,754] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:27:58,896] INFO api.views.data_delete_view - Intenté eliminar el registro con ID: aabbcc3
[2025-04-09 21:27:58,935] INFO api.views.data_delete_view - Eliminé exitosamente el registro con ID: aabbcc3
[2025-04-09 21:27:58,936] INFO django.server - "DELETE /api/data/delete/aabbcc3/ HTTP/1.1" 204 64
[2025-04-09 21:34:16,258] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:34:41,673] INFO django.server - "GET /swagger/ HTTP/1.1" 200 2214
[2025-04-09 21:34:42,359] INFO django.server - "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
[2025-04-09 21:34:42,366] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
[2025-04-09 21:34:42,379] INFO django.server - "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
[2025-04-09 21:34:42,668] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
[2025-04-09 21:34:42,745] INFO django.server - "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
[2025-04-09 21:34:42,765] INFO django.server - "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
[2025-04-09 21:34:42,799] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
[2025-04-09 21:34:42,851] INFO django.server - "GET /swagger/?format=openapi HTTP/1.1" 200 1901
[2025-04-09 21:34:42,867] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
[2025-04-09 21:35:10,534] INFO django.server - "GET /redoc/ HTTP/1.1" 200 928
[2025-04-09 21:35:10,557] INFO django.server - "GET /static/drf-yasg/style.css HTTP/1.1" 304 0
[2025-04-09 21:35:10,562] INFO django.server - "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
[2025-04-09 21:35:10,578] INFO django.server - "GET /static/drf-yasg/redoc-init.js HTTP/1.1" 200 2566
[2025-04-09 21:35:10,595] INFO django.server - "GET /static/drf-yasg/redoc/redoc.min.js HTTP/1.1" 200 1042511
[2025-04-09 21:35:10,728] INFO django.server - "GET /redoc/?format=openapi HTTP/1.1" 200 1901
[2025-04-09 21:35:10,810] INFO django.server - "GET /static/drf-yasg/redoc/redoc-logo.png HTTP/1.1" 200 4969
[2025-04-09 21:38:11,421] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 21:38:11,879] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:38:16,259] INFO django.server - "GET /swagger/ HTTP/1.1" 200 2214
[2025-04-09 21:38:16,266] INFO django.server - "GET /static/drf-yasg/style.css HTTP/1.1" 304 0
[2025-04-09 21:38:16,268] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
[2025-04-09 21:38:16,268] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
[2025-04-09 21:38:16,269] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
[2025-04-09 21:38:16,269] INFO django.server - "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
[2025-04-09 21:38:16,271] INFO django.server - "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
[2025-04-09 21:38:16,271] INFO django.server - "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
[2025-04-09 21:38:16,319] INFO django.server - "GET /swagger/?format=openapi HTTP/1.1" 200 1901
[2025-04-09 21:38:16,322] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
[2025-04-09 21:38:21,808] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\settings.py changed, reloading.
[2025-04-09 21:38:22,256] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:39:43,886] INFO django.utils.autoreload - C:\Users\Jordán\Desktop\Pruebas\P3_RESTful_API\medical_api\urls.py changed, reloading.
[2025-04-09 21:39:44,322] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-04-09 21:39:49,687] INFO django.server - "GET /swagger/ HTTP/1.1" 200 2214
[2025-04-09 21:39:49,694] INFO django.server - "GET /static/drf-yasg/style.css HTTP/1.1" 304 0
[2025-04-09 21:39:49,696] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
[2025-04-09 21:39:49,696] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
[2025-04-09 21:39:49,697] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
[2025-04-09 21:39:49,697] INFO django.server - "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
[2025-04-09 21:39:49,699] INFO django.server - "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
[2025-04-09 21:39:49,699] INFO django.server - "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
[2025-04-09 21:39:49,730] INFO django.server - "GET /swagger/?format=openapi HTTP/1.1" 200 1831
[2025-04-09 21:39:49,731] INFO django.server - "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
[2025-04-09 21:45:33,626] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:45:33,627] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-id-1
[2025-04-09 21:45:33,630] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: pytest-id-1
[2025-04-09 21:45:33,630] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 1
[2025-04-09 21:45:33,634] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:45:33,634] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-duplicate-id
[2025-04-09 21:45:33,636] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: pytest-duplicate-id
[2025-04-09 21:45:33,636] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 1
[2025-04-09 21:45:33,636] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:45:33,636] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-duplicate-id
[2025-04-09 21:45:33,637] WARNING django.request - Bad Request: /api/data/upload/
[2025-04-09 21:46:57,845] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:46:57,846] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-id-1
[2025-04-09 21:46:57,849] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: pytest-id-1
[2025-04-09 21:46:57,849] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 1
[2025-04-09 21:46:57,854] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:46:57,854] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-duplicate-id
[2025-04-09 21:46:57,855] INFO api.views.data_upload_view - Entrada válida. Guardé en base de datos con ID: pytest-duplicate-id
[2025-04-09 21:46:57,855] INFO api.views.data_upload_view - Finalicé procesamiento. Todas las entradas se guardaron correctamente. Total: 1
[2025-04-09 21:46:57,856] INFO api.views.data_upload_view - Inicié procesamiento del JSON recibido en POST.
[2025-04-09 21:46:57,856] INFO api.views.data_upload_view - Procesando entrada con clave: 1 y ID: pytest-duplicate-id
[2025-04-09 21:46:57,857] WARNING django.request - Bad Request: /api/data/upload/
[2025-04-09 21:46:58,015] INFO api.views.data_retrieve_view - Inicié la consulta de datos con filtros opcionales.
[2025-04-09 21:46:58,016] INFO api.views.data_retrieve_view - Finalicé la consulta. Total de registros encontrados: 0
